export const assetData = {
  fruitsAndVegetables: [
    "/vector_icons/fruits-and-vegetables/Artichokes from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Arugula from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Asparagus from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Avocado from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Bamboo Shoot.png",
    "/vector_icons/fruits-and-vegetables/Beets from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Bitter Gourd.png",
    "/vector_icons/fruits-and-vegetables/Bok Choy.png",
    "/vector_icons/fruits-and-vegetables/Broccoli from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Brussels Sprouts.png",
    "/vector_icons/fruits-and-vegetables/Cabbage from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Carrot (1).png",
    "/vector_icons/fruits-and-vegetables/Cauliflower (1).png",
    "/vector_icons/fruits-and-vegetables/Celery from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Chard from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Collard Green.png",
    "/vector_icons/fruits-and-vegetables/Corn from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Cucumber from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Dandelion Green.png",
    "/vector_icons/fruits-and-vegetables/Eggplant Vegetable.png",
    "/vector_icons/fruits-and-vegetables/Elephant Foot Yam.png",
    "/vector_icons/fruits-and-vegetables/Endive from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Fennel from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Fenugreek Leaves.png",
    "/vector_icons/fruits-and-vegetables/Garlic (1).png",
    "/vector_icons/fruits-and-vegetables/Ginger Vegetable.png",
    "/vector_icons/fruits-and-vegetables/Green Bean.png",
    "/vector_icons/fruits-and-vegetables/Jicama from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Kale from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Kohlrabi from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Leeks from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Lettuce from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Mushroom from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Mustard Greens.png",
    "/vector_icons/fruits-and-vegetables/Okra from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Onion.png",
    "/vector_icons/fruits-and-vegetables/Parsnips from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Peas from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Pepper from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Potato from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Pumpkin from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Radicchio (1).png",
    "/vector_icons/fruits-and-vegetables/Radish from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Rhubarb from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Rutabaga from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Spinach from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Squash from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Sweet Potato.png",
    "/vector_icons/fruits-and-vegetables/Tomato from Recraft.png",
    "/vector_icons/fruits-and-vegetables/Watercress from Recraft.png",
    "/vector_icons/fruits-and-vegetables/White Mushroom.png",
    "/vector_icons/fruits-and-vegetables/Zucchini from Recraft.png",
    "/vector_icons/fruits-and-vegetables/apple.png"
  ],
  health: [
    "/vector_icons/health/3d Health(1).png",
    "/vector_icons/health/3d Health(2).png",
    "/vector_icons/health/3d Health(3).png",
    "/vector_icons/health/3d Health(4).png",
    "/vector_icons/health/3d Health(5).png",
    "/vector_icons/health/3d Health(6).png",
    "/vector_icons/health/3d Health(7).png",
    "/vector_icons/health/3d Health(8).png",
    "/vector_icons/health/3d Health(9).png",
    "/vector_icons/health/3d Health(10).png",
    "/vector_icons/health/3d Health(11).png",
    "/vector_icons/health/3d Health(12).png",
    "/vector_icons/health/3d Health(13).png",
    "/vector_icons/health/3d Health(14).png",
    "/vector_icons/health/3d Health(15).png",
    "/vector_icons/health/3d Health(16).png",
    "/vector_icons/health/3d Health(17).png",
    "/vector_icons/health/3d Health(18).png",
    "/vector_icons/health/3d Health(19).png",
    "/vector_icons/health/3d Health(20).png",
    "/vector_icons/health/3d Health(21).png",
    "/vector_icons/health/3d Health(22).png",
    "/vector_icons/health/3d Health(23).png",
    "/vector_icons/health/3d Health(24).png",
    "/vector_icons/health/3d Health(25).png",
    "/vector_icons/health/3d Health(26).png",
    "/vector_icons/health/3d Health(27).png",
    "/vector_icons/health/3d Health(28).png",
    "/vector_icons/health/3d Health(29).png",
    "/vector_icons/health/3d Health(30).png",
    "/vector_icons/health/3d Health(31).png",
    "/vector_icons/health/3d Health(32).png",
    "/vector_icons/health/3d Health(33).png",
    "/vector_icons/health/3d Health(34).png",
    "/vector_icons/health/3d Health(35).png",
    "/vector_icons/health/3d Health(36).png",
    "/vector_icons/health/3d Health(37).png",
    "/vector_icons/health/3d Health(38).png",
    "/vector_icons/health/3d Health(39).png",
    "/vector_icons/health/3d Health(40).png",
    "/vector_icons/health/3d Health(41).png",
    "/vector_icons/health/3d Health(42).png",
    "/vector_icons/health/3d Health(43).png",
    "/vector_icons/health/3d Health(44).png",
    "/vector_icons/health/3d Health(45).png",
    "/vector_icons/health/3d Health(46).png",
    "/vector_icons/health/3d Health(47).png",
    "/vector_icons/health/3d Health(48).png",
    "/vector_icons/health/3d Health(49).png"
  ],
  equipment: [
    "/vector_icons/Badge.png",
    "/vector_icons/Dumbell.png",
    "/vector_icons/Gym Plate.png",
    "/vector_icons/Kettlebell.png",
    "/vector_icons/Ring.png",
    "/vector_icons/Standing Speed Ball.png",
    "/vector_icons/Stop Watch.png",
    "/vector_icons/Weight Scale.png",
    "/vector_icons/Wheel Roller.png",
    "/vector_icons/almirah.png",
    "/vector_icons/barrels.png",
    "/vector_icons/bottle.png",
    "/vector_icons/cycle.png",
    "/vector_icons/dumblle.png",
    "/vector_icons/energy_drink.png",
    "/vector_icons/fitness_ball.png",
    "/vector_icons/mat.png",
    "/vector_icons/skipping_rope.png",
    "/vector_icons/smart_watch.png",
    "/vector_icons/tredmill.png",
    "/vector_icons/weight_machine.png",
    "/vector_icons/wheele_roller.png",
    "/vector_icons/yoga_ball.png"
  ]
};
